services:
  data-generator:
    image: local/influx-data-generator
    build:
      context: generator
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_HOST=http://influxdb:8086
    restart: on-failure:5
    depends_on:
      influxdb:
        condition: service_healthy
  grafana:
    image: grafana/grafana-oss:11.6.0
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    restart: on-failure:5
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  influxdb:
    image: influxdb:2.7.4
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    ports:
      - "8086:8086"
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    restart: on-failure:5
volumes:
  grafana-storage: {}
  influxdb2-data: {}
  influxdb2-config: {}
